---

- name: Install vault enterprise
  become: true
  block:

    - name: Add hashicorp release yum repo
      ansible.builtin.yum_repository:
        name: hashicorp
        description: Hashicorp Stable - $basearch
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey: https://rpm.releases.hashicorp.com/gpg

    - name: Install vault package
      ansible.builtin.package:
        name: vault-enterprise
        state: present

    - name: Install vault enterprise license to /etc/vault.d
      ansible.builtin.copy:
        src: "{{ vault.license }}"
        dest: /etc/vault.d/vault.hclic
        owner: vault
        group: vault
        mode: '0640'

    - name: Install vault enterprise configuration
      ansible.builtin.template:
        src: "{{ vault.config }}.j2"
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: '0640'

    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      community.crypto.openssl_privatekey:
        path: "{{ vault.ssl.key }}"
        owner: vault
        group: vault
        mode: '0640'

    - name: Check whether certificate exists
      ansible.builtin.stat:
        path: "{{ ca.certificate_path }}"
      register: certificate_exists

    - name: Read existing certificate if exists
      ansible.builtin.slurp:
        src: "{{ ca.certificate_path }}"
      when: certificate_exists.stat.exists
      register: certificate

    - name: Generate a new certificate signing request for vault
      community.crypto.openssl_csr:
        path: "{{ vault.ssl.csr }}"
        privatekey_path: "{{ vault.ssl.key }}"
        common_name: "{{ inventory_hostname }}"
        organization_name: "Red Hat"
        organizational_unit_name: "NA"
        state_or_province_name: "NC"
        locality_name: "Raleigh"
        subject_alt_name:
          - "DNS:localhost"
          - "DNS:{{ ansible_fqdn }}"
          - "IP:127.0.0.1"
          - "IP:{{ ansible_default_ipv4.address }}"
        owner: vault
        group: vault
        mode: '0640'

    - name: Sign ssl certificate and key for vault
      community.crypto.x509_certificate:
        path: "{{ vault.ssl.cert }}"
        privatekey_path: "{{ vault.ssl.key }}"
        csr_path: "{{ vault.ssl.csr }}"
        provider: ownca
        ownca_path: "{{ ca.certificate_path }}"
        ownca_privatekey_path: "{{ ca.privatekey_path }}"
        ownca_not_after: +365d  # valid for one year
        ownca_not_before: "-1d"  # valid since yesterday
        owner: vault
        group: vault
        mode: '0640'

    - name: Start and enable vault service
      ansible.builtin.service:
        name: vault
        state: started
        enabled: true

...
