---
vault_provision_redhat_subscription: false
vault_provision_redhat_username: ''
vault_provision_redhat_password: ''

vault_provision_rhel_update: true
vault_provision_rhel_repos:
  - rhel-9-for-x86_64-baseos-rpms
  - rhel-9-for-x86_64-appstream-rpms

vault_provision_rhel_packages:
  - openssl
  - python3-cryptography
  - yum-utils

vault_provision_epel_gpg_key_url: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
vault_provision_epel_rpm_url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
vault_provision_epel_packages:
  - python3-hvac
