---

- name: Set access token for API access
  become: true
  ansible.builtin.shell:
    cmd: >
      gitlab-rails runner "token = User.find_by_username('root').personal_access_tokens.create(scopes: ['api'], name: 'Ansible Automation token', expires_at: 365.days.from_now); token.set_token('{{ gitlab_admin_password }}'); token.save!"
  register: token_create_output
  listen:
    - Setup_api_token

- name: Update system ssl trust db
  ansible.builtin.command:
    cmd: update-ca-trust
  become: true

- name: Reconfigure gitlab
  become: true
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure


- name: Restart gitlab nginx
  become: true
  ansible.builtin.command:
    cmd: gitlab-ctl restart nginx

...
